### ISSUE TITLE
[Perfil de Twitter] Visualizacion de foto de Portada - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#19]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Seleccionar en la parte izquierda de la pagina web la opcion PERFIL</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27842.png" alt="" />| | Pass |
| 2| Esperar que cargue correctamente el PERFIL</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27844.png" alt="" />| | Pass |
| 3| Clic en foto de portada en cualquier lugar de la foto</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27851.png" alt="" />| | Pass |
| 4| Aparece ventana emergente con foto cargada en pantalla completa</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27852.png" alt="" />| | Fail |

**Comment by CeronMayo** [comment]
No aparecio la foto de portada

![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_27907.png)

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D13](https://aceronm.testquality.com/project/12907/result/2566631/defect/8997).

**Comment by JefferssonMunozTorres** [comment]
Se reviso código fuente de javascript que carga la foto, se soluciono bug al arreglar etiquetas de id. Volver a realizar prueba.
