### ISSUE TITLE
[Twitter Chat] CC003 - Error de enviar un archivo  .pdf - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#20]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Buscamos el Archivo .rar a enviar dentro del chat de twitter.</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27892.png" alt="" />| | Pass |
| 2| Se verifica que no se puede enviar archivo .pdf, muestra mensaje de solo foto, video o gif.</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27895.png" alt="" />| | Fail |

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D14](https://aceronm.testquality.com/project/12907/result/2566649/defect/8998).

**Comment by jmsanchezl** [comment]
No esta permitido enviar archivos PDF en esta red social.
