### ISSUE TITLE
[Interaccion con tercero] Visualizar comentarios de Twit - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#21]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Bucar boton de "INICIO" para ver twits de terceros</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27866.png" alt="" />| | Pass |
| 2| Escoger twit a experimentar</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27868.png" alt="" />| | Pass |
| 3| Clic en cualquier espacio dentro del twit donde aparesca el cursor de la manito| | Pass |
| 4| Se abrira otra pagina con los comentario del twit</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27876.png" alt="" />| | Fail |

**Comment by CeronMayo** [comment]
No esta cargando la misma cantidad indicada de comentarios que existen

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D15](https://aceronm.testquality.com/project/12907/result/2566641/defect/8999).

**Comment by JefferssonMunozTorres** [comment]
Se reviso respuesta de backend con respecto a la carga de la pagina de respuesta para los comentarios.
