### ISSUE TITLE
[Interaccion con tercero] Dar like - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#22]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Bucar boton de "INICIO" para ver twits de terceros</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27866.png" alt="" />| | Pass |
| 2| Escoger twit a experimentar</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27868.png" alt="" />| | Pass |
| 3| Hacer clic en el corazon o el numero del contador del tweet</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27894.png" alt="" />| | Pass |
| 4| Posterior al clic se resalta el like y se aumenta el contador </p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27896.png" alt="" />| | Fail |

**Comment by CeronMayo** [comment]
No hubo cambio en el contador de likes de la publicacion

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D17](https://aceronm.testquality.com/project/12907/result/2566643/defect/9001).

**Comment by JefferssonMunozTorres** [comment]
Se corrigió error de contador en tiempo real. Bug con código Javascript para la pagina web. Volver a realizar prueba.
