### ISSUE TITLE
[Publicacion de Twit] CP002 - Repetir Publicación de Tweet - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#24]
#### Precondition
Escribe el Tweet (hasta 280 caracteres) en el cuadro para redactar un Tweet ubicado en la parte superior de la cronología de inicio, o haz clic en el botón Twittear ubicado en la barra de navegación. Puedes incluir hasta 4 fotos, un archivo GIF o un video en tu Tweet.
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Para publicar debemos dar Click en el botón "Tweet".</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27840.png" alt="" />| | Fail |
| 2| Redactar la publicación que se enviará.</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27841.png" alt="" />| | Fail |
| 3| Se muestra error porque no se puede repetir la misma Publicación.</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27843.png" alt="" />| | Fail |

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D18](https://aceronm.testquality.com/project/12907/result/2566635/defect/9002).

**Comment by jmsanchezl** [comment]
Se verifica que para el alcance no esta permitido repetir una mismo comentario para no generar un bug.
