### ISSUE TITLE
[Publicacion de Twit] CP003 - Cantidad de Caracteres en una Publicación de Tweet - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#25]
#### Precondition
Conocida antaño como la red social de los 140 caracteres, hace tiempo que los aumentaron para permitir expresarse un poco mejor y ahora son 280 los caracteres que soporta cada tuit
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Click en el botón "Tweet"</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27856.png" alt="" />| | Fail |
| 2| Redactar más de 300 Caracteres en el campo permitido.</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27860.png" alt="" />| | Fail |
| 3| Se verifica que el botón de Tweet se deshabilita y se pinta de rojo al carácter 281 en adelante.</p><br><p><img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27861.png" alt="" />| | Fail |

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D19](https://aceronm.testquality.com/project/12907/result/2566636/defect/9003).

**Comment by jmsanchezl** [comment]
Se procedió con realizar una actualización de caracteres de 140  a 280 para mejorar la interacción con el usuario.
