### ISSUE TITLE
[Busqueda en Twitter] Buscar personas en twitter - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#26]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Ingresar usuario <a href="&#x6d;&#97;&#x69;&#x6c;&#x74;&#x6f;&#x3a;&#119;&#105;&#107;&#105;&#x68;&#111;&#119;&#115;&#x74;ev&#x65;&#x40;&#103;&#109;a&#105;&#108;&#x2e;&#x63;&#111;&#109;">w&#105;&#x6b;&#x69;&#104;&#111;&#119;&#115;&#x74;&#101;&#x76;&#x65;&#64;&#103;&#109;&#x61;&#x69;&#108;&#x2e;c&#111;&#109;</a>| | Pass |
| 2| Ingresar contraseña " 1234 "| | Pass |
| 3| pulsar el boton <strong>Ingresar</strong>| | Pass |
| 4| Ingresar el nombre de la persona a buscar | <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_27885.png" alt="" />| Fail |

**Comment by CeronMayo** [comment]
Ingrese el nombre de la persona que deseaba buscar en twitter pero el intento tubo una falla adjunto al evidencia.
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_27912.png)

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D20](https://aceronm.testquality.com/project/12907/result/2566640/defect/9005).

**Comment by buer91** [comment]
Se realizo las pruebas respectivas para solucionar el problema.

**Comment by buer91** [comment]
Se realizo las pruebas respectivas para solucionar el problema.
