### ISSUE TITLE
[Inicio de Sesion] Inicio de sesión con Apple - Fail

### ISSUE THREAD

**Issue by CeronMayo** [CeronMayo/Twitter_GrupoAzul#28]
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Ingresa usuario <a href="&#109;&#x61;&#105;&#108;&#116;o&#58;&#119;&#x69;&#107;&#105;&#x68;&#x6f;&#119;&#115;&#116;&#x65;&#118;&#101;&#64;&#x67;&#109;&#x61;&#x69;&#108;&#46;&#x63;o&#109;">&#119;&#105;k&#x69;&#x68;&#111;&#x77;&#x73;&#x74;&#x65;&#118;&#x65;&#x40;&#103;&#x6d;&#x61;&#x69;l&#x2e;&#x63;&#x6f;&#x6d;</a>| | Pass |
| 2| Ingresa contraseña "1234"| | Pass |
| 3| Dale en el boton <strong>Ingresar</strong>| | Fail |

**Comment by CeronMayo** [comment]
Ingrese mi usuario y contraseña pero hubo un error adjunto la evidencia
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_27914.png)

**Comment by CeronMayo** [comment]
https://aceronm.testquality.com defect [D22](https://aceronm.testquality.com/project/12907/result/2566628/defect/9007).

**Comment by buer91** [comment]
Se actualizo el codigo y se  repitieron las pruebas y se soluciono el problema.

**Comment by buer91** [comment]
Se actualizo el codigo y se repitieron las pruebas y se soluciono el problema.
